name: Selenium with TestNG - CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule: ## Schedule the job to run at 12.am daily.
    - cron: '0 12 * * *'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
     
    - uses: browser-actions/setup-chrome@latest
    - run: chrome --version

    - name: Set Suite XML File
      run: echo "SUITE_XML_FILE=XMLFiles/cesSuite.xml" >> $GITHUB_ENV

    - name: Build with Maven
      run: mvn -B clean test -DsuiteXmlFiles=${{ env.SUITE_XML_FILE }}
